driver:
  name: vagrant

provisioner:
  name: chef_zero
  # We have tests that ensure our deprecated features still
  # work so we can't turn this on globally.
  # deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6.9
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.8
  - name: debian-9.0
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: freebsd-10
  - name: freebsd-11

suites:
  - name: resources
    run_list:
      - recipe[test::resources]
  - name: global
    run_list:
      - recipe[logrotate::global]
